# Apply to all files without commiting:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate
default_language_version:
    python: python3.8
repos:
-   repo: https://github.com/python-poetry/poetry
    rev: 1.6.0
    hooks:
    -   id: poetry-check
    # -   id: poetry-lock
    -   id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt"]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-ast
    -   id: fix-byte-order-marker
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    # -   id: detect-aws-credentials
    # -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v0.942
#     hooks:
#     -   id: mypy
#         args: [--ignore-missing-imports]
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]
-   repo: https://github.com/asottile/blacken-docs
    rev: 1.16.0
    hooks:
    -   id: blacken-docs
        # additional_dependencies: [black==20.8b1]
### Needs argument for diasabling line_length
### https://github.com/jackdewinter/pymarkdown/blob/main/docs/rules/rule_md013.md
-   repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.12
    hooks:
    -   id: pymarkdown
        args:
        -   --config=.pymarkdown.json
        # -   --disable-rules
        # -   line-length,no-inline-html
        -   scan
